candidate_name = input("Enter your name: ")
candidate_age = int(input("Enter your age: "))
utme_score = int(input("Enter your score"))
result_sitting = input("Did you obtain your o_level result at first sitting (Yes/No): ").lower()
o_level_subject = input("Enter five O'Level including english and math: ").title().split(",")
o_level_grade = input("Enter grade with a minimum grade of C6 with result obtained at one sitting").upper().split(",")
o_level_result = dict(zip(o_level_subject, o_level_grade))
post_utme_eligibility = candidate_age >= 16 and utme_score >= 200 and result_sitting = "yes" and o_level_result[o_level_grade] = ("A1" or "B2" or "B3" or "C4" or "C6" or "C5")
print(f"Student Eligibile for post utme: {post_utme_eligibility}")
post_utme_score = input("post utme score: ")